project:
  type: website

website:
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "1. Runde"
        menu:
          - href: runde_1/aufgabe_1/index.qmd
            text: 1. Aufgabe
          - href: runde_1/aufgabe_2/index.qmd
            text: 2. Aufgabe

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

execute:
  freeze: auto